### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ghost** [CaryLandholt/AngularFun#15]
Hmmm....I see your to-do list includes a screencast. Maybe an addendum to this could be comments in the code that explain what's happening? 

Cheers

**Comment by CaryLandholt** [comment]
Lol, @timothybone,

You got me on that one.  I will improve.

Cary

**Comment by CaryLandholt** [comment]
@timothybone I have created a [documentation](https://github.com/CaryLandholt/AngularFun/tree/documentation) branch with a stab at greatly improving overall documentation of the project.

I started with the [grunt.js](https://github.com/CaryLandholt/AngularFun/blob/documentation/grunt.js) file.

I'm certainly not done, but any advice would be much appreciated.

Thanks,
Cary

**Comment by ghost** [comment]
Cool! I'll take a look at it. This project is great by the way
