### ISSUE TITLE
problems with jasmine test (on windows?)

### ISSUE THREAD

**Issue by ranmacar** [CaryLandholt/AngularFun#16]
Hi Cary,
Trying to run Jasmine tests, but having trouble.
The first ssue is a missing domReady.js in /dist/scripts/libs after building with grunt.
When I manually supply a domReady.js, it hangs on twitterfy.js calling angular - for some reason it is loaded before angular is in the test runner. I tried adding a dependency to main.coffee, but don't really know how to use require.js

The runner then shows 1 Error: No module: app
and in the inspector i can see: 
Uncaught ReferenceError: angular is not defined      twitterfy.js:2

Running on Chrome/Win8
Thanks!

**Comment by CaryLandholt** [comment]
Hi @ranmacar,

It does look like something is broken.
I'm working on a fix right now but won't have anything until the weekend sometime.

Sorry about that.

Cary

**Comment by CaryLandholt** [comment]
@ranmacar,

The tests should work fine now.  Since we don't really need the capabilities of RequireJS for the tests, I've gone ahead and removed it.

Include your spec scripts in the runner.html file.

Please let me know if this helps.

Thanks,
Cary

**Comment by ranmacar** [comment]
Thanks! Will look at it and tell you. Amazing job on the whole project by the way, learning a ton of angular from it. Thanks a lot :)

**Comment by ranmacar** [comment]
Sorry, didnt get to it sooner. Works great now.
