### ISSUE TITLE
"reload" task incompatible?

### ISSUE THREAD

**Issue by knalli** [CaryLandholt/AngularFun#18]
I'm currently not sure what exactly here is wrong.

At first, I had adapted the configuration w/ live reload into my setup, but this does not work. After that, I had checked out now the AngularFun repo, but the live reload won't work either.

I'm using the latest Chrome (stable/release channel, aka 24 atm). The Chrome Extension "LiveReload" is 2.0.9.

The browser logged this

```
LiveReload protocol error (unparsable JSON) after receiving data: 
"{ command: 'hello', protocols: [ '[http://livereload.com/protocols/official-7](http://livereload.com/protocols/official-7)', '[http://livereload.com/protocols/2.x-origin-version-negotiation](http://livereload.com/protocols/2.x-origin-version-negotiation)', '[http://livereload.com/protocols/2.x-remote-control](http://livereload.com/protocols/2.x-remote-control)'], serverName: 'grunt-reload', }".. 
```

And the server logged this

```
Received Message: 
{"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","ext":"Chrome","extver":"2.0.9"}
Fri Jan 18 2013 23:19:31 GMT+0100 (CET) Peer 127.0.0.1 disconnected.
```

Any ideas? Is the current setup still working for you?

**Comment by CaryLandholt** [comment]
Make sure the reload port is different than the port you're serving your app.
Also the port inside the reload configuration is the default one used by the reload plugin.  They must match.

``` JavaScript
reload: {
  liveReload: true,
  port: 35729
}
```

Thanks,
Cary

**Comment by knalli** [comment]
Sure. I'm using the current HEAD of this repository :) And the logs in my previous comment -- so would I guess -- show that both client and server are talking to each other (port matches).

This means the setup is working for you? What a version of chrome and LiveReload do you have?

**Comment by CaryLandholt** [comment]
I'm running:
- Google Chrome 24.0.1312.52
- [LiveReload 2.0.9](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei)

In order for LiveReload to work with the project you must:
- run `grunt dev` to ensure the grunt tasks watch for file changes
- run `grunt server`
- ensure that the Chrome extension is enabled on the site (see screenshot)

![image](https://f.cloud.github.com/assets/833972/80425/f36ad992-6258-11e2-82eb-7e793c33a7e2.png)

I just tried the above, and it is working for me with the latest code.

Please let me know if this helps.

Thanks,
Cary

**Comment by knalli** [comment]
Well, now it works. Both AngularFun and my own project. I cannot say I have something changed. Too much strange stuff today..

**Comment by CaryLandholt** [comment]
At least it's working.  :)
