### ISSUE TITLE
Compass integration

### ISSUE THREAD

**Issue by knalli** [CaryLandholt/AngularFun#19]
In our app, we use Compass instead of Less. Should I PR this? As an alternative to less (not replacement)?

**Comment by CaryLandholt** [comment]
Compass is an alternative.
Creating a Compass branch would be more appropriate, unless you identify other issues that make Compass integration difficult.

Thanks,
Cary

**Comment by knalli** [comment]
It's not difficult. I'm only thinking about putting this altogether. Then it would be only a change of the tasks in the aggregators default, dev and prod.

-Jan

**Comment by CaryLandholt** [comment]
ok - let me know if you need help
I recommend creating a branch for Compass

Thanks Jan,
Cary

**Comment by knalli** [comment]
Okay, I've made a new branch on my fork: https://github.com/knalli/AngularFun/tree/compass-integration
Currently, this replaces less completely and uses https://github.com/vwall/compass-twitter-bootstrap

What do you think?

**Comment by CaryLandholt** [comment]
I cloned the compass-integration branch and received a grunt error on the compass task.

![image](https://f.cloud.github.com/assets/833972/80740/eaf87c58-628d-11e2-8e21-3ce7add8e1f1.png)

Is it a requirement to have compass installed globally?

One of my design principles was to keep global requirements at a minimum.  Can this be done?

Thanks

**Comment by CaryLandholt** [comment]
Ahh - I just saw you updated the README with the requirement.
Let me give it another go.

**Comment by knalli** [comment]
Yep, this is required. Compass (or SASS) is "Ruby land", there is currently no other way.

**Comment by CaryLandholt** [comment]
The prerequisite has a typo.
It currently reads `gem install gem`
I'm pretty sure you mean `gem install compass'
Correct?

**Comment by knalli** [comment]
Yes, of course. :(

**Comment by CaryLandholt** [comment]
And need `gem install bundler` as a prerequisite

**Comment by knalli** [comment]
But only if you want to use it. You don't have it. Bundler is like an optional -NPM- package.json.

**Comment by CaryLandholt** [comment]
Right, I was just going through your docs step-by-step.
After installing bundler, I'm able to get it to work.
I was able to run all three build configurations successfully and even picked up my changes in dev mode.

Nice job!
