### ISSUE TITLE
'html' module not found

### ISSUE THREAD

**Issue by davidmarble** [CaryLandholt/AngularFun#21]
2 issues:
1. The `html` module should be included in packages.json (I think -- I'm not a node dev)
2. In the "Run It" section of your readme, you should mention you must compile using one of the options listed before running it for the first time (I'm new to grunt)

Details: `npm install` worked fine, so far as I could tell, but upon running `grunt server` and browsing to the page, I got an error that the `html` module could not be found. I stopped the server and installed it via `npm install html`. I restarted the server, and realized I probably needed to compile with `grunt` when I got a template error. Runs fine now.

**Comment by CaryLandholt** [comment]
@davidmarble,

hmm, that's very strange.
You shouldn't need to install the html package.  What version of node are you running?
Are you still having trouble?

Good point about adding the compile precondition before "Running It".  I'll add it to the readme.

Thanks for the feedback,
Cary

**Comment by davidmarble** [comment]
Latest node (0.8.18). Followed everything else (global install of coffee-script and grunt). But like I said, `npm install html` fixed it for me.

**Comment by CaryLandholt** [comment]
strange, I'll keep an eye out.

By the way, I updated the docs to add the compilation precondition before running.  :)

**Comment by CaryLandholt** [comment]
@davidmarble,

This actually happened to me recently when upgrading express.js and grunt.js.
After completing the upgrade the error went away.
