### ISSUE TITLE
RequireJS text plugin

### ISSUE THREAD

**Issue by AjaxSolutions** [CaryLandholt/AngularFun#24]
Cary, I don't see that you are using the RequireJS text plugin.  This plugin could be used to load AngularJS templates instead of using templateURL.  As much as I understand AngularJS, templates are loaded via Ajax whereas RequireJS optimization can inline text file which is more efficient as it eliminates the need to make an http request.
Les

**Comment by CaryLandholt** [comment]
There is an inlineTemplate grunt task which wraps the views in [script](http://docs.angularjs.org/api/ng.directive:script) tags and places them in the index.html file.
This is done in the prod build and avoids the additional requests.

I'm working on a grunt task that places the views directly in the [$templateCache](http://docs.angularjs.org/api/ng.$templateCache).

**Comment by CaryLandholt** [comment]
Also, using the text plugin requires the use of RequireJS in production.  This can be avoided altogether.
