### ISSUE TITLE
Requirejs and loading jquery, jquery plugins

### ISSUE THREAD

**Issue by sidthesloth** [CaryLandholt/AngularFun#25]
Hi Cary,
I'm using angularfun as a reference for a huge application. I have struggled in vain to configure AMD enabled jquery and NON AMD jquery plugins like datatables and the controllers to load. Do you perhaps have some pointers into how I could go about loading the jquery and the plugins?. 

Thank you.

**Comment by CaryLandholt** [comment]
Hi @sidthesloth,

I created a [nonAMD](https://github.com/CaryLandholt/AngularFun/tree/nonAMD) branch demonstrating how to load a non AMD file as a dependency and have AngularJS manage it through its dependency management system.

Steps
- Added [jquery.coffee](https://github.com/CaryLandholt/AngularFun/blob/nonAMD/src/scripts/values/jquery.coffee) to register jquery with AngularJS using the [value](http://docs.angularjs.org/api/angular.Module) module type.
- Modified [twitterController.coffee](https://github.com/CaryLandholt/AngularFun/blob/nonAMD/src/scripts/controllers/twitterController.coffee) (used as an example) to include jquery as a dependency (this can be done because of the prior step) and added a snippet of jQuery to display a message in the page h1.
- Added values/jquery shim with dependencies on app and libs/jquery in [main.coffee](https://github.com/CaryLandholt/AngularFun/blob/nonAMD/src/scripts/main.coffee).
- Added values/jquery as a dependency for controllers/twitterController.

You can now run the app.

Please let me know if this helps.

Thanks,
Cary

**Comment by sidthesloth** [comment]
Hi Cary,
Your quick response is much appreciated and thank you for the solution.
Just some further questions however, is this the only way of loading
jquery?...from my understanding jQuery supports the AMD API by
conditionally wrapping itself in a define() method and declaring
itself as _named
AMD module_, so it should work by say using the requirejs config such as
below, right?

require

  # Sets the js folder as the base directory for all future relative paths
  baseUrl: "./js"

  # 3rd party script alias names (Easier to type "jquery" than
"libs/jquery, etc")
  paths:

```
# Core Libraries
jquery: "libs/jquery"
```

# Includes Desktop Specific JavaScript files here (or inside of your

Desktop router)
require ["jquery"], ($) -> console.log "Hey look, I'm using jQuery with
Require.js!"

And then for the non AMD jquery plugins load them as you have done.

Second question - for line  $('h1').html "jQuery #{jqueryVersion} loaded!"
isnt it this using what is termed a common pitfall on the angularJS FAQ
which says that, quote

```
          "Stop trying to use jQuery to modify the DOM in controllers.
```

Really. That includes adding elements, removing elements, retrieving their
contents, showing
               and hiding them. Use built-in directives, or write your own
where necessary, to do your DOM manipulation. See below about duplicating
functionality."

regards
sidthesloth

**Comment by CaryLandholt** [comment]
Lol - you are absolutely right about modifying DOM with jQuery inside controllers.  I do not recommend doing so at all.  I was just demonstrating how to register a 3rd-party library with RequireJS and AngularJS.

Perhaps it was a bad example for the reason that you actually don't want to do it.

Nevertheless, latter versions of jQuery do provide a define which makes jQuery available as a module.

I believe the following code will give you what you're looking for.  You can see it in action [here](http://plnkr.co/edit/tIX9fmN7fTjyOIc5L22p?p=preview).

``` JavaScript
require({
  paths: {
    jquery: 'http://code.jquery.com/jquery-1.9.1.min',
    qtip: 'http://craigsworks.com/projects/qtip_new/packages/nightly/jquery.qtip'
  },
  shim: {
    qtip: {
      deps: ['jquery'] /* dependencies for jquery.qtip */
    }
  }
}, ['jquery', 'qtip'], function (jq) {
  // we want a handle to jquery
  // and the jquery.qtip to be loaded
  // 
  // notice there is no need to pass
  // jquery.qtip as a parameter

  jq('a[title]').qtip();
});
```

Please let me know if this helps.

Thanks,
Cary

**Comment by sidthesloth** [comment]
Thanks a great deal, I just needed to confirm my understanding, I'm still
getting my config to work

**Comment by CaryLandholt** [comment]
Let me know if you need additional help.

**Comment by sidthesloth** [comment]
Hi Cary,

I managed to configure the Jquery, thanx,  however when trying to configure
angulaui when I add the ui module to the app.coffee file as follows

angular.module 'app', ['ngResource', 'ui']

the added ui module causes this error in the javascript console Error: No
module: ui @ http://localhost:3005/scripts/libs/angular.js:1058

do you perhaps know what is wrong?

Regards
sidthesloth

**Comment by CaryLandholt** [comment]
Can you share your repo?

At first blush it sounds like the angular-ui module is not available when the app is being bootstrapped.
This [line](https://github.com/CaryLandholt/AngularFun/blob/master/src/scripts/main.coffee#L18) shows that app has a dependency on libs/angular and libs/angular-resource.  You may need to include the ui module here too.

Without seeing the full context of your code, it is a bit tricky to know.

Thanks - let me know if I can see the code.

**Comment by sidthesloth** [comment]
Spot on Cary!!! ...and how did i miss it ...this is where pair programming
would come in handy. After including the ui module everything works :)
...oh the value of opensource and collaborative development. Thanx a great
deal.

**Comment by CaryLandholt** [comment]
Awesome!  Yeah, I love pair programming and OSS too.
