### ISSUE TITLE
Is the loading of files with the shim configuration still asynchronous and as fast as how you did it in take 2?

### ISSUE THREAD

**Issue by JustGoscha** [CaryLandholt/AngularFun#29]

**Comment by CaryLandholt** [comment]
Yes - RequireJS handles shimmed modules the same as defined modules.
They are asynchronous in the [dev build](https://github.com/CaryLandholt/AngularFun#compile-angular-fun) and synchronous in the [prod build](https://github.com/CaryLandholt/AngularFun#compile-angular-fun).
All scripts are compiled into a single minified file with the prod build.
