### ISSUE TITLE
What changes needed to deploy to other webservers?

### ISSUE THREAD

**Issue by pkrnjevic** [CaryLandholt/AngularFun#36]
Overall, a very nice starting point - the best I've seen so far.

But, while  node.js is fine for development, I'd prefer to deploy using a different web server, perhaps Apache or nginx, fronting a Python/Ruby/Go app.

Can you suggest what changes are needed?

Thanks,
Peter

**Comment by CaryLandholt** [comment]
This was actually one of my principles.  You don't need to make any changes unless your api url's are different.

Once the application is built by `grunt` or `grunt prod`, just take the contents of the dist folder and host them in whichever web server you wish.

When running `grunt server` only the files in the dist server are hosted.

Does this help?

Thanks,
Cary

**Comment by pkrnjevic** [comment]
I think so. Before opening this question, I did try running against my laptop's Apache but it didn't work - not surprising since i set no config, particularly a web root.
I'll try again shortly.

**Comment by CaryLandholt** [comment]
You will need to make sure the web server serves the index.html file as well as images, scripts, and styles.

**Comment by pkrnjevic** [comment]
Of course index.html served just fine - the problem was all the other folders were searched from the wrong root.

**Comment by CaryLandholt** [comment]
Good point, the paths are root-relative.

**Comment by pkrnjevic** [comment]
Hi Cary,

Just cleaned up my apache config and now deploying from dist works flawlessly!
Nice job.

Thanks,
Peter

**Comment by CaryLandholt** [comment]
Great!
