### ISSUE TITLE
How about Jade?

### ISSUE THREAD

**Issue by pkrnjevic** [CaryLandholt/AngularFun#37]
I grew to quite like haml on a recent rails project and would like to use Jade with AngularJS.
Not quite sure how to integrate the necessary grunt/node pieces to get this done.
Any tips?

**Comment by CaryLandholt** [comment]
There is a [grunt-contrib-jade](https://github.com/gruntjs/grunt-contrib-jade) grunt plugin which can do what you want.

You would compile your jade files using the above task.  This can be incorporated into the build where the templates are compiled currently

**Comment by pkrnjevic** [comment]
That's the part I don't quite understand - the role of the templates. I see they're html, but also compiled. Can this be replaced by jade? Or is this to do with loading them into the template cache?

**Comment by CaryLandholt** [comment]
The templates are compiled using a grunt task from [grunt-hustler](https://github.com/CaryLandholt/grunt-hustler).

With this you can use underscore templating functions as well as functions provided by the template task, such as hashing for cache busting.  See https://github.com/CaryLandholt/AngularFun/blob/master/src/index.template#L15-L16.

If you don't use any of these features, plain html is all you'll need.

**Comment by pkrnjevic** [comment]
Nice. I'll experiment a bit and see if i can combine templates with jade.
Thanks again!

**Comment by CaryLandholt** [comment]
Cool

**Comment by pkrnjevic** [comment]
Hi Cary,

Last night I had a crack at Jade support, though I broke cacheing and IE in the process. I'll try to fix them asap.
You can see the changes in my fork (https://github.com/pkrnjevic/AngularFun.git).
If you have any suggestions on how to fix IE and cacheing, I would be most appreciative.
Thanks again for the wonderful angularjs seed!

Cheers,
Peter

**Comment by pkrnjevic** [comment]
NB: I should have mentioned the jade mods are all in a new branch: jade.

**Comment by CaryLandholt** [comment]
That's pretty cool, Peter.

You are missing the necessary IE conditional comments to support IE.
https://github.com/pkrnjevic/AngularFun/blob/master/src/index.template#L2
Looks like this style of syntax works.

``` jade
//if lt IE 7
  html.no-js.lt-ie9.lt-ie8.lt-ie7(xmlns:ng='http://angularjs.org', xmlns:app='ignored')
```

Within the template grunt task there is a config.has function that computes the hash of a given file based on its contents.  Since you are not using the template grunt task, you are missing this capability.
https://github.com/pkrnjevic/AngularFun/blob/master/src/index.template#L13

**Comment by pkrnjevic** [comment]
Hi Cary,

In my working copy I did add back a couple of lines for IE, though as yet untested:

```
//if lte IE 7
    script(src='http://cdnjs.cloudflare.com/ajax/libs/json2/20110223/json2.js')
//if lte IE 8
    script(src='//html5shiv.googlecode.com/svn/trunk/html5.js')
```

Don't know if they work - I'll probably just use yours ;-)

And thanks for the tip about the hashes - will be needed for prod version, once I get through transforming a ton of legacy JS and jquery into something a bit more Angular-friendly.

Cheers,
Peter

**Comment by CaryLandholt** [comment]
Hey @pkrnjevic,

I've added jade support in AngularFun.  Take a look at v2.0.0.

Thanks,
Cary

**Comment by pkrnjevic** [comment]
Hi Cary,

Very nice to see you're still updating this - I've been hacking away at your version from 4 months ago, and it'll be good to rebase to your new version, especially since I never really addressed IE8 or compressing everything for production.

I've also started using coffeescript classes for services. My approach, after much experimentation, is a bit different from yours. 
Here's a sample gist: https://gist.github.com/pkrnjevic/6348746
I'd love to hear what you think...

Keep up the great work!

Cheers,
Peter

**Comment by CaryLandholt** [comment]
Cool - actually I just started using CoffeeScript classes too.
https://github.com/CaryLandholt/AngularFun/blob/master/src/scripts/services/gitHubService.coffee

**Comment by pkrnjevic** [comment]
I saw that: your approach is certainly a quick way to migrate existing Angular services, by doing everything in the constructor.

My approach feels more like traditional CoffeeScript, though it took a few attempts to find something that felt (and worked!) right.

I'd be curious to hear what you think of this approach - I haven't seen anyone else doing it like this.

**Comment by CaryLandholt** [comment]
How would you handle directives with your approach?

**Comment by pkrnjevic** [comment]
Haven't gotten that far yet :smile:
