### ISSUE TITLE
Don't do a "grunt clean"!

### ISSUE THREAD

**Issue by pkrnjevic** [CaryLandholt/AngularFun#38]
Being a long-time C dev, i figure "make clean" or anything similar should be pretty benign.
Then the good folks developing grunt come along and, by default, run all targets.
I now know I should have done a "grunt clean:working" but that was only after wiping my .coffee files, then learning about how grunt works. (as much as I could learn in half and hour or so).

I guess the proper answer here is for me to learn my tools before experimenting.
Btw, no biggy since I'm obsessive with git and had everything saved.

**Comment by CaryLandholt** [comment]
lol - yeah, be careful with grunt clean
