### ISSUE TITLE
loading external files

### ISSUE THREAD

**Issue by sidthesloth** [CaryLandholt/AngularFun#39]
Hi 
How is loading external json/text data file using $http.get and or reading data from database done?

**Comment by CaryLandholt** [comment]
I'm using the [angular-resource.js](http://docs.angularjs.org/api/ngResource.$resource) library which is an abstraction over $http.

You can see it in use with [personService](https://github.com/CaryLandholt/AngularFun/blob/master/src/scripts/services/personService.coffee).

``` CoffeeScript
# the following sets up a resource to /people/:id where id is an optional parameter
Person = $resource './people/:id'

# get all people from the server
Person.get()

# get person with id 1 from the server
Person.get(1)
```

When you execute `grunt server` in AngularFun, a Node.js web server fires up and provides routing located in [routes.coffee](https://github.com/CaryLandholt/AngularFun/blob/master/routes.coffee).  This is just dummy data for AngularFun.  You would, of course, provide access to your own server data.

It is recommended that your server then read from the database and return the result to the web app.
