### ISSUE TITLE
Using a CDN?

### ISSUE THREAD

**Issue by laurelnaiad** [CaryLandholt/AngularFun#43]
Hi, Cary.

Thanks for this template.  I'd like to be able to reference cdnjs copies of angular, etc., so that I can take advantage of them possibly being in a browser's cache already.  For some reason it doesn't seem to be working for me.  I suspect I'm doing something silly.

I specified paths in main.js and in the requirejs section of Gruntfile.js:

```
paths: {
 'libs/angular': '//cdnjs.cloudflare.com/ajax/libs/angular.js/1.1.3/angular.min'
}
```

The only result I see is that when I build dev, the file is indeed fetched from the cdn (according to chrome developer tools) but nothing actually runs and I get a blank page.  And when I build prod the minified js doesn't contain the string "cdnjs"...

Is there a way to specify non-local js files?  Ideally I'd reference a local non-minified copy for dev builds and the minified cdnjs copy for prod.

I thought I could do this because of the require docs:
https://github.com/jrburke/r.js/blob/master/build/example.build.js#L37

**Comment by CaryLandholt** [comment]
Sorry for the delay, Stu.
I'll be providing a solution in the next couple days.

Thanks,
Cary

**Comment by CaryLandholt** [comment]
Delay apologies.  :(

I've been working heavily on a large AngularJS application at work.

Outside of including the reference directly in index.html, the current AngularFun architecture does not support CDNs.
The motivation was to create a single, minified JavaScript file.

Sorry.

Cary

**Comment by laurelnaiad** [comment]
Thanks, Cary.  No worries.  I've long since moved on :)
