### ISSUE TITLE
copying tests

### ISSUE THREAD

**Issue by laurelnaiad** [CaryLandholt/AngularFun#44]
I added this to the copy section in order to get the spec files into dist_test:

```
      }, {
        cwd: './test/',
        src: 'scripts/**/*.js',
        dest: './dist_test/',
        expand: true
      }
```

I'm a total newbie so perhaps that shouldn't have been needed?

Edit: to demonstrate my level of newbieness -- I can't even make the tests fail now that they are run...I edited test/scripts/services/personSpec.js as so, and it still succeeds.

```
  return it('should query for people at /people and receive an array', function() {
    var failure, success;
    success = function(result) {
      return false;

      // expect(result).toEqualData([
      //   {
      //     name: 'George'
      //   }
      // ]);
    };
    failure = function() {
      return expect(true).toBe(false);
    };
    return personService.get(success, failure);
  });

```

**Comment by CaryLandholt** [comment]
Hi @stu-salsbury,

I've reworked the testing configuration, and I believe it is much simpler.
There's no need to copy anymore.  :)

Check it out.

Thanks,
Cary
