### ISSUE TITLE
Template management.

### ISSUE THREAD

**Issue by nistormihai** [CaryLandholt/AngularFun#47]
For stat very good tutorial application for angularjs and requirejs mashup.
The only issue witch I have is with template management.
So well Take 3 was perfect for management of coding and coding style but for templates,
I really don't like having all templates in one file, for multiple reasons.
And I don't like having to rely on angular to load my templates on router mode also.

I really wanted to work with requirejs for this, to use the r.js to build some parts of templates and other just to leave them as they are.

but yet I didn't find any viable solution to this.
What are your thoughts on this?

**Comment by CaryLandholt** [comment]
Hey @nistormihai,

Sorry it took so long to reply.

I'm not so concerned with _what_ loads the templates as long as they are ready when the app needs them.
That said, I do like a snappy user experience, so I'm included to favor the template cache method (see ngTemplateCache) so the templates are already in memory when the app needs them.

I hope to include a new templating mechanism in AngularFun sometime.
