### ISSUE TITLE
Run issue on Windows

### ISSUE THREAD

**Issue by msimonc** [CaryLandholt/AngularFun#5]
Hi Cary,

Had to use: grunt.cmd to compile, but that didn't work when Running it.  
Also tried from Cygwin.

Trace is:

J:\ProjJS\AngularFun-master>grunt.cmd server
Running "server:app" (server) task
20 Nov 16:43:50 - [nodemon] v0.6.23
20 Nov 16:43:50 - [nodemon] watching: J:\ProjJS\AngularFun-master
20 Nov 16:43:50 - [nodemon] starting `coffee.cmd ./server.coffee --watch ./routes.coffee`
CreateProcessW: The system cannot find the file specified.
20 Nov 16:43:50 - [nodemon] app crashed - waiting for file changes before starting...

Windows 8 Eval version, 64bit

Thanks!

**Comment by CaryLandholt** [comment]
@msimonc I'm assuming you have all the prerequisites installed.
- [node.js](http://nodejs.org/) (minimum version 0.8.1)
- npm (should be installed as part of node.js)
- CoffeeScript package `npm install -g coffee-script`
- Grunt package `npm install -g grunt`
- `npm install` to install all of the packages referenced in package.json

By the way, I just committed some updates to the project within the last two hours.

Please let me know.  In the meantime, I will install the project on Windows myself.

Thanks,
Cary

**Comment by msimonc** [comment]
My bad:  npm install -g coffee-script

Thanks!

**Comment by CaryLandholt** [comment]
Great!  Thanks for checking it out @msimonc
