### ISSUE TITLE
Support ui-bootstrap

### ISSUE THREAD

**Issue by malixsys** [CaryLandholt/AngularFun#50]
I cannot seem to be able to add ui-bootstrap properly: baybe because it doesn't follow the angular-\* pattern?

**Comment by CaryLandholt** [comment]
@malixsys,

I've created a branch that includes ui-bootstrap.
https://github.com/CaryLandholt/AngularFun/tree/ui-bootstrap-integration

**Steps**
- Add angular-bootstrap to [bower.json](https://github.com/CaryLandholt/AngularFun/blob/ui-bootstrap-integration/bower.json#L10)
- Add a [copy](https://github.com/CaryLandholt/AngularFun/blob/ui-bootstrap-integration/Gruntfile.coffee#L83-L87) configuration to the Gruntfile to copy the angular-bootstrap bower components to the working directory
- Include the file to the [karma](https://github.com/CaryLandholt/AngularFun/blob/ui-bootstrap-integration/Gruntfile.coffee#L209) configuration in the Gruntfile to be able to test.  I'm hoping to remove this need in the future.
- Include the ui.bootstrap module as part of the [ngShim](https://github.com/CaryLandholt/AngularFun/blob/ui-bootstrap-integration/Gruntfile.coffee#L257) configuration in the Gruntfile.  This is what actually includes the module when firing up the web server

You'll need to trigger bower to pull down the ui-bootstrap components from the cloud.  `bower install`

_AngularFun is currently using Bootstrap 3.  It looks like ui-bootstrap is caught up yet._

Let me know if it makes sense.

Cary

**Comment by malixsys** [comment]
Fantastic! Could not get it to load ui-boottstrap for some reason...

Thanks!!
