### ISSUE TITLE
hashed filenames and css

### ISSUE THREAD

**Issue by maru1034sk** [CaryLandholt/AngularFun#56]
Hi.

Images are being hashed:

```
glyphicons-halflings.png -> glyphicons-halflings.6c8829cc6f.png
```

How is it possible to reference to hashed image filenames in a *.less file?

**Comment by CaryLandholt** [comment]
Prior to upgrading to Bootstrap 3, I had a working version for images in less files.

``` JavaScript
<% if (config.environment === 'prod') { %>
    @iconSpritePath:          "<%= config.getHashedFile('./.temp/images/glyphicons-halflings.png', {trim: './.temp'}) %>";
    @iconWhiteSpritePath:     "<%= config.getHashedFile('./.temp/images/glyphicons-halflings-white.png', {trim: './.temp'}) %>";
<% } else { %>
    @iconSpritePath:          "../images/glyphicons-halflings.png";
    @iconWhiteSpritePath:     "../images/glyphicons-halflings-white.png";
<% } %>
```

It uses the same mechanism as is done in index.html.

See the full repo when that configuration was live.
https://github.com/CaryLandholt/AngularFun/tree/f8f5bd4d137bf8819a986041150b932b9a4c18c4

There is a new/better way coming very soon, however.

**Comment by maru1034sk** [comment]
@CaryLandholt thank you for the help/explanation :) This way works for me.

**Comment by CaryLandholt** [comment]
Cool - I hope the _next way_ will work even better.  :)
