### ISSUE TITLE
issue with Running "less:app" (less) task

### ISSUE THREAD

**Issue by beninfobelt** [CaryLandholt/AngularFun#57]
Having issues using grunt command after a clean install:
1. Cloned AngularFun
2. command: sudo npm install
3. command: bower install
4. command: grunt jslove
5. command: grunt

Running "clean:working" (clean) task

Running "coffeelint:files" (coffeelint) task

> > 0 files lint free.

Running "copy:app" (copy) task
Created 10 directories, copied 22 files

Running "ngShim:scripts" (ngShim) task

> > Source file " ./.temp/scripts/libs/angular-animate.min.js" not found.
> > Source file " ./.temp/scripts/libs/angular-resource.min.js" not found.
> > Source file " ./.temp/scripts/libs/angular-route.min.js" not found.

Running "coffee:app" (coffee) task
File .temp/scripts/app.js created.
File .temp/scripts/app.js.map created.
File .temp/scripts/bootstrap.js created.
File .temp/scripts/bootstrap.js.map created.
File .temp/scripts/main.js created.
File .temp/scripts/main.js.map created.

Running "less:app" (less) task

> > FileError: 'bootstrap.less' wasn't found in ./.temp/styles/styles.less on line 1, column 1:
> > 1 @import "bootstrap.less";
> > 2

benjamin@benjamin-Aspire-V3-571:~/workspace/AngularFun$ bower -version
1.2.6
benjamin@benjamin-Aspire-V3-571:~/workspace/AngularFun$ grunt -version
grunt-cli v0.1.8
grunt v0.4.1
benjamin@benjamin-Aspire-V3-571:~/workspace/AngularFun$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=13.04
DISTRIB_CODENAME=raring
DISTRIB_DESCRIPTION="Ubuntu 13.04"
NAME="Ubuntu"
VERSION="13.04, Raring Ringtail"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 13.04"
VERSION_ID="13.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by beninfobelt** [comment]
one thing I notice is that after running the commands mentioned above (and inspecting the index.html), I do not see the libs folder in my scripts directory. I also am missing the main.js file

**Comment by CaryLandholt** [comment]
Hi @beninfobelt,

It looks like you have both grunt-cli and bower installed globally.  That's good.

``` bash
benjamin@benjamin-Aspire-V3-571:~/workspace/AngularFun$ bower -version
1.2.6
benjamin@benjamin-Aspire-V3-571:~/workspace/AngularFun$ grunt -version
grunt-cli v0.1.8
grunt v0.4.1
```

Can you verify that the bower components did pull down properly?
A bower_components directory should have been created at the root of your project.

It should contain
- angular
- angular-animate
- angular-mocks
- ...
- requirejs

**Comment by beninfobelt** [comment]
Hey Cary - sorry for the delay in posting - I have been in transit this week in Charlotte.

I just checked and do not have the bower_components directory

I tried to run the bower install command but it doesn't seem to be doing anything. After running bower install, I try the grunt command again and get the same error (while the bower_components directory is still missing)

What set of commands do I need to deploy in order to pull down the bower_components directory?

**Comment by CaryLandholt** [comment]
Perhaps you have an outdated bower installed globally.

Make sure you see the bower.json file in the project first.

Then enter the following at the command line.

``` bash
npm install -g bower
npm update -g bower
bower install
```

Let me know.

Thanks

**Comment by beninfobelt** [comment]
Here is the contents of the bower.json

{
    "name": "app",
    "version": "0.0.0",
    "dependencies": {
        "angular": "1.2.0-rc.2",
        "angular-animate": "1.2.0-rc.2",
        "angular-mocks": "1.2.0-rc.2",
        "angular-resource": "1.2.0-rc.2",
        "angular-route": "1.2.0-rc.2",
        "bootstrap": "~3.0.0",
        "html5shiv": "~3.6.2",
        "json3": "~3.2.5",
        "requirejs": "~2.1.8"
    }
}

Just went through these while in the AngularFun directory

npm install -g bower
npm update -g bower
bower install

But got the same result after the bower install command and the grunt command

Running "less:app" (less) task

> > FileError: 'bootstrap.less' wasn't found in ./.temp/styles/styles.less on line 1, column 1:
> > 1 @import "bootstrap.less";
> > 2
> > Warning: Error compiling LESS. Use --force to continue.

Aborted due to warnings.
benjamin@benjamin-Aspire-V3-571:~/workspace/AngularFun$ bower -version
1.2.6

I know that grunt-cli, for example, requires rollback to 1.8 instead of 1.9 - perhaps the same sort of thing needs to happen for bower?

**Comment by CaryLandholt** [comment]
Strange you had to rollback grunt-cli.  I recently updated it on my machine.

Have you tried deleting the project node_modules and performing a new `npm install`?

Maybe there's some junk laying around.

**Comment by beninfobelt** [comment]
I tried to delete the node_module directory and run npm install again. But to no avail.

Then, I tried to do a clean from the start clone but ran into the same issues.

I need to spend time learning coffee script.

Here is the latest I've found on status re: grunt-cli@0.1.9:
https://github.com/gruntjs/grunt-cli/issues/26

**Comment by CaryLandholt** [comment]
Have you performed a fresh clone of the AngularFun repository to an empty directory?
This could eliminate issues with old/outdated files?

**Comment by faloi** [comment]
I had the same issue and realised that the **bower_components** folder is being created inside the app folder (I'm trying to find out why) . So simply moving it from there to the root directory did the trick!

**Comment by CaryLandholt** [comment]
Where is the "app" folder?

**Comment by faloi** [comment]
It's created in the root directory after running **grunt**, i.e. instead of having _AngularFun/bower_components_ I have _AngularFun/app/bower_components_

**Comment by CaryLandholt** [comment]
Is the package.json file at the root of the AngularFun directory?

**Comment by faloi** [comment]
Yep, I didn't change anything. Just run _git clone_ followed by _npm install_ like you said in the README

**Comment by CaryLandholt** [comment]
Very strange - sounds like it might be an issue with bower.
I keep my eyes open for a solution.

Thanks for the feedback!

Cary

**Comment by faloi** [comment]
Great, let me know if you need some extra info (bower/npm versions, OS, etc)

**Comment by CaryLandholt** [comment]
Do you have the latest AngularFun code?
I committed code recently to use a grunt task to install bower components.

**Comment by faloi** [comment]
If by latest you mean 15-minutes-ago then the answer is yes. I've just tried starting from scratch but came up with the same error :confused:

**Comment by CaryLandholt** [comment]
lol - ok

Can you try this?

Please comment out `copy: false` from the bower.install.options configuration.
And add `targetDir: './bower_components'` in the same spot.

**Comment by faloi** [comment]
Same thing, it generated _app/bower_components_ again

**Comment by CaryLandholt** [comment]
argh - do you have access to another machine?  Maybe non Linux?

**Comment by faloi** [comment]
I have a Win7 VM here, give me some minutes to try there

**Comment by CaryLandholt** [comment]
Great - thanks, Federico!

**Comment by faloi** [comment]
Weird, but worked like a charm on Windows. Same versions of npm (1.3.8), grunt (0.4.1) and grunt-cli (0.1.9) on both OSs. My host OS is Ubuntu 13.04 64bits

**Comment by CaryLandholt** [comment]
very strange - sounds like an issue with bower and Ubuntu, perhaps

Thanks for checking

Do you mind submitting an issue to the bower folks?

**Comment by faloi** [comment]
Sure, I'll do it tomorrow (it's 1am here in Argentina and I'm falling asleep). I'm very very newbie on the nodejs ecosystem, so perhaps you can help me to improve the problem description. I'll email you a draft copy of the ticket before submitting it!

**Comment by CaryLandholt** [comment]
Muchas gracias. Buenas noches.

Espero con interés trabajar con usted.

Cary

**Comment by faloi** [comment]
Jajajaj gracias, continuamos mañana

**Comment by beninfobelt** [comment]
I can confirm the same - on my linux machine, the bower_components directory is nested underneath the app directory.

Though I wasn't able to edit bower.install.options configuration  - - - - where is this file located?

Pls post the link to your bower ticket Federico - I will compound the issue so we get more attention to it.

**Comment by CaryLandholt** [comment]
The settings are in Gruntfile.coffee, near the top

**Comment by beninfobelt** [comment]
Ah - Threw me at first bc I didn't realize that this file gets converted to Gruntfile.js after running jslove

I hope I inserted the comment syntax correctly:

```
grunt.initConfig
    bower:
        install:
            options:
                # copy: false
                targetDir: './bower_components'
        uninstall:
            options:
                cleanBowerDir: true
                copy: false
                install: false

    # Deletes dist and .temp directories
```

So I cloned a fresh copy. After making this edit, I ran the commands mentioned above but received the same error and the bower_components folder is nested underneath the app directory

FileError: 'bootstrap.less' wasn't found

**Comment by CaryLandholt** [comment]
Ok, bummer.

I have to run to my day job. I'll keep searching for a solution. 

Thanks,
Cary

**Comment by beninfobelt** [comment]
I'm not sure that the issue is related to bower_components folder is being created inside the app folder

Other projects I've started with Yeoman have this setup and have no issues.

**Comment by beninfobelt** [comment]
of course - me too

you've titled the project well :)

let me know what I can do to help test along the way

i look forward to contributing once I get coffee script under my belt

**Comment by CaryLandholt** [comment]
Hey, @beninfobelt, @janraasch just committed a change for getting bower to work consistently.
A .bowerrc file was added indicating where to place the bower_components.

Please let me know if this works.

**Comment by faloi** [comment]
@CaryLandholt it works for me, thanks!

**Comment by CaryLandholt** [comment]
Awesome!

**Comment by beninfobelt** [comment]
Awesome! I was able to successfully pull up angular fun in Chrome (on my ubuntu linux box) after running these commands on a clean install:

Cloned AngularFun
command: sudo npm install
command: bower install
command: grunt jslove
command: grunt

Thank you greatly Cary.

All the best,

-Ben

**Comment by CaryLandholt** [comment]
Great, @beninfobelt!
