### ISSUE TITLE
app crashes when running grunt server

### ISSUE THREAD

**Issue by talgiat** [CaryLandholt/AngularFun#6]
getting this on trying to run the app:
Running "server:app" (server) task
3 Dec 01:22:26 - [nodemon] v0.6.23
3 Dec 01:22:26 - [nodemon] watching: /Users/talgiat/Dropbox/Dev/Projects/AngularFun
3 Dec 01:22:27 - [nodemon] starting `coffee ./server.coffee --watch ./routes.coffee`
3 Dec 01:22:27 - [nodemon] app crashed - waiting for file changes before starting...
execvp(): No such file or directory

**Comment by CaryLandholt** [comment]
Hi @talgiat,

Sorry to hear you're having trouble.

Please verify that you have satisfied the prerequisites.

## Prerequisites
- Must have [Git](http://git-scm.com/) installed
- Must have [node.js (at least v0.8.1)](http://nodejs.org/) installed with npm (Node Package Manager)
- Must have [CoffeeScript](https://npmjs.org/package/coffee-script) node package installed globally.  `npm install -g coffee-script`
- Must have [Grunt](https://github.com/gruntjs/grunt) node package installed globally.  `npm install -g grunt`

and that you have installed all of the npm packages via `npm install`

Are you working off of the latest AngularFun source code?
What OS are you using?

Thanks,
Cary

**Comment by talgiat** [comment]
Ah, my bad, didn't have the CoffeeScript package installed.

works like charm now.

Thanks !

**Comment by CaryLandholt** [comment]
Great - I'll close the issue.
Please let me know if you encounter anything else.

**Comment by sidthesloth** [comment]
Thank you for this great application reference architecture, Its People like you that continue to support the open-source paradigm by sharing your knowledge.

**Comment by CaryLandholt** [comment]
Thanks @sidthesloth!
