### ISSUE TITLE
using stateProvider from ui-router

### ISSUE THREAD

**Issue by sidthesloth** [CaryLandholt/AngularFun#61]
Hi,
I have substituted $routeProvider with $stateProvider from ui-router in order to make use of nested views. However, I get Error [ng:areq] http://errors.angular.org/undefined/ng/areq?p0=calendarController&p1=not%20a%20function%2C%20got%20undefined.
I have tried all the forms of defining controllers for the templates in the router shown in the ui-router documentation but cannot get it to work. 

this does not work

.state 'home'
    url: "/home"
    views:
       "home"
           templateurl:"views/partials/home.html"
           controller: "calendarController"

Can you perhaps suggest how to do this if any?, help much appreciated

**Comment by CaryLandholt** [comment]
Hi @sidthesloth,

I've created a new [ui-router](https://github.com/CaryLandholt/AngularFun/tree/ui-router) branch, replacing angular-route with ui-router.

It's in a working condition.

Please let me know if it helps.

Thanks,
Cary

**Comment by sidthesloth** [comment]
Hi Cary

Thank you, it indeed helped and all the assistance is much appreciated.

**Comment by CaryLandholt** [comment]
Great!
