### ISSUE TITLE
Heroku production

### ISSUE THREAD

**Issue by MattCowski** [CaryLandholt/AngularFun#65]
After `git push heroku master`:

`heroku open` opens the app on http://still-dusk-6074.herokuapp.com/ 

```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

Is there anything specific I need to change to use Heroku as production?

**Comment by CaryLandholt** [comment]
Without knowing your Heroku setup, I really couldn't tell.

What kind of backend are you using?  Node.js, Rails, etc.

Are you trying to push the entire project or only the files necessary for Heroku to run the application?

**Comment by MattCowski** [comment]
(updated issue ^^)

Not using the backend yet. Just trying to see if _anything_ will show up. 
I'm pushing the entire project.

Basically, my question is: What are the steps to get this stock / default AngularFun to run on Heroku? (Just to see the example tabs directives with github / people controller etc)

**Comment by CaryLandholt** [comment]
You'll need to push the contents of the **dist** folder, which is created after running `grunt prod`.
Heroku will need to be setup to respond with index.html as the default document.  <- I would think this is a default Heroku configuration.

**Comment by CaryLandholt** [comment]
Only push the contents of dist
