### ISSUE TITLE
npm install fail on linux

### ISSUE THREAD

**Issue by cve** [CaryLandholt/AngularFun#66]
Hi, I'm trying to run it on my local environment, I have node installed and other requirements, but the npm fails with error included on the screen
![screen](https://f.cloud.github.com/assets/594384/1778515/ada5c35c-6835-11e3-9480-95abdbcaaacc.png)

**Comment by CaryLandholt** [comment]
I've noticed this happens on Windows machines. Can you confirm you're using Windows?

Try running grunt bower:install at the command line.

**Comment by CaryLandholt** [comment]
Sorry, I just noticed you mentioned Linux. Which distro?

**Comment by cve** [comment]
Kubuntu 13.10

**Comment by CaryLandholt** [comment]
Can you confirm if grunt bower:install works?

**Comment by cve** [comment]
Hmm, grunt bower:install gives me error that this command not exists in my system, but I've just install it with npm install -g grunt a few minutes ago...

**Comment by CaryLandholt** [comment]
Ahh. Try npm install -g grunt-cli

**Comment by cve** [comment]
Ok, bower:install works, but now there is another problem:

![screen1](https://f.cloud.github.com/assets/594384/1778730/0725aac0-6839-11e3-8ed4-b13e7b884cca.png)

**Comment by CaryLandholt** [comment]
Yeah, I'm aware of that issue. You actually can ignore it. Should be good to go.

**Comment by cve** [comment]
Yeah it works! cool :) thank you very much

**Comment by CaryLandholt** [comment]
Awesome!
