### ISSUE TITLE
How to set my own bootstrap.js ?

### ISSUE THREAD

**Issue by nmathon** [CaryLandholt/AngularFun#68]
I need to modify bootstrap.js in order to wrap angular.bootstrap in a google.load function.
How can I do that ?

``` javascript
google.load('visualization', '1', {
  'callback':function(){ 
    angular.bootstrap(document, ['app']); 
  }, 
  packages: ['corechart', 'treemap']
});
```

**Comment by nmathon** [comment]
I found a solution but not sure it's the good one.
I removed 'NGBOOTSTRAP' in shimmer requirements and writed my own bootstrap.js in src/scripts
Is this the right way ?

**Comment by CaryLandholt** [comment]
You can write your own bootstrap file and register it with the `shimmer` configuration.
Sounds like you might be doing this already.

Create a file called `bootstrap.coffee` or `bootstrap.js` in `src/scripts`.

Then change the `require` value in the `shimmer` configuration to:

``` coffee
require: 'bootstrap'
# was require: 'NGBOOTSTRAP'
```

`NGBOOTSTRAP` is a reserved value that corresponds to the following content.

``` coffee
angular.element(window.document).ready ->
    angular.bootstrap window.document, ['app']
```

**Comment by nmathon** [comment]
Thanks, It works.
