### ISSUE TITLE
grunt build fatal error

### ISSUE THREAD

**Issue by dino-** [CaryLandholt/AngularFun#71]
Trying to follow the README, I encounter this error when issuing any grunt command:

> ```
> $ grunt build
> Running "clean:working" (clean) task
> 
> Running "bower:install" (bower) task
> >> Cleaned target dir /home/dino/dev/AngularFun/.components
> Fatal error: Arguments to path.join must be strings
> ```

I'm very new to all of this, Angular, web development, these tools like npm and grunt, so please let me know if you need more info about my system (Linux) and versions of things.

**Comment by CaryLandholt** [comment]
@dino- 

Please give it another try

**Comment by dino-** [comment]
Same thing is happening. I did a fresh clone and followed the instructions in the README. Wondering if there's something cached in my ~, but I have no idea where to look.

**Comment by CaryLandholt** [comment]
Please try the following:
1. delete `node_modules`
2. `git pull`
3. `npm install`
4. attach a screen shot of the problem, if it doesn't work

**Comment by dino-** [comment]
I can reproduce it. Starting with nothing downloaded:

> ```
> $ git clone https://github.com/CaryLandholt/AngularFun.git
> 
> Cloning into 'AngularFun'...
> remote: Reusing existing pack: 4421, done.
> remote: Counting objects: 4, done.
> remote: Compressing objects: 100% (4/4), done.
> remote: Total 4425 (delta 0), reused 0 (delta 0)
> Receiving objects: 100% (4425/4425), 3.99 MiB | 2.41 MiB/s, done.
> Resolving deltas: 100% (1251/1251), done.
> Checking connectivity... done.
> 
> $ cd AngularFun/
> $ npm install
> 
> npm http GET https://registry.npmjs.org/grunt-contrib-clean
> npm http GET https://registry.npmjs.org/grunt-bower-task
> npm http GET https://registry.npmjs.org/grunt-contrib-connect
> npm http GET https://registry.npmjs.org/grunt-coffeelint
> npm http GET https://registry.npmjs.org/grunt
> npm http GET https://registry.npmjs.org/grunt-contrib-copy
> npm http GET https://registry.npmjs.org/grunt-contrib-coffee
> ```

... lots and lots of stuff ...

> ```
> ├── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.15)
> ├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
> └── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
> 
> grunt-contrib-imagemin@0.7.1 node_modules/grunt-contrib-imagemin
> ├── pretty-bytes@0.1.1
> ├── async@0.7.0
> ├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
> └── imagemin@0.4.6 (get-stdin@0.1.0, stat-mode@0.2.0, ware@0.2.1, image-type@0.1.4, tempfile@0.1.3, nopt@2.2.1, rimraf@2.2.8, fs-extra@0.8.1, imagemin-svgo@0.1.0, imagemin-jpegtran@0.1.0, imagemin-pngquant@0.1.2, imagemin-optipng@0.1.0, imagemin-gifsicle@0.1.1)
> 
> $ grunt build
> 
> Running "clean:working" (clean) task
> 
> Running "bower:install" (bower) task
> >> Cleaned target dir /home/dino/dev/AngularFun/.components
> Fatal error: Arguments to path.join must be strings
> 
> 
> Execution Time (2014-07-18 16:16:03 UTC)
> bower:install  1.4s .. 99%
> Total 1.4s
> 
> $ node --version
> 
> v0.10.28
> 
> $ npm --version
> 
> 1.4.9
> 
> $ bower --version
> 
> 1.3.8
> 
> $ grunt --version
> 
> grunt-cli v0.1.13
> grunt v0.4.5
> ```

**Comment by CaryLandholt** [comment]
Hmmm. Ok, what does grunt build --verbose show?

**Comment by dino-** [comment]
> $ grunt build --verbose

A lot of things ending with `...OK` and then:

> Cleaned target dir /home/dino/dev/AngularFun/.components
> bower not-cached git://github.com/angular/bower-angular-animate.git#1.2.20
> bower resolve git://github.com/angular/bower-angular-animate.git#1.2.20
> bower not-cached git://github.com/angular/bower-angular-mocks.git#1.2.20
> bower resolve git://github.com/angular/bower-angular-mocks.git#1.2.20
> bower not-cached git://github.com/angular/bower-angular-route.git#1.2.20
> bower resolve git://github.com/angular/bower-angular-route.git#1.2.20
> bower not-cached git://github.com/aFarkas/html5shiv.git#3.7.2
> bower resolve git://github.com/aFarkas/html5shiv.git#3.7.2
> bower cached git://github.com/angular/bower-angular.git#1.2.20
> bower validate 1.2.20 against git://github.com/angular/bower-angular.git#1.2.20
> bower cached git://github.com/twbs/bootstrap.git#3.2.0
> bower validate 3.2.0 against git://github.com/twbs/bootstrap.git#3.2.0
> bower cached git://github.com/bestiejs/json3.git#3.3.2
> bower validate 3.3.2 against git://github.com/bestiejs/json3.git#3.3.2
> bower cached git://github.com/jrburke/requirejs-bower.git#2.1.14
> bower validate 2.1.14 against git://github.com/jrburke/requirejs-bower.git#2.1.14
> Fatal error: Arguments to path.join must be strings
> 
> Execution Time (2014-07-18 21:25:53 UTC)
> loading tasks   4ms  0%
> clean:working   5ms  0%
> bower:install  1.1s   99%
> Total 1.1s

**Comment by CaryLandholt** [comment]
Let's go ahead and pair on this one.
Let me know when's a good time.

**Comment by CaryLandholt** [comment]
I've been able to replicate this on a Windows machine.
Mac works fine.

Still looking into this.

**Comment by CaryLandholt** [comment]
@dino-, I think I've figured it out, and it's a bizarre one.

When bower is first installed and executed on your machine, it asks if you will grant it rights to track analytics.

Since bower is executed from within grunt, there is no opportunity to reply to this request.

This would be why some machines work and some don't, as you may or may not have bower installed.

So, please try the following.

``` bash
$ cd AngularFun
$ npm install -g bower
$ bower install
# respond to the prompt
$ grunt
```

Please let me know if this helps.

**Comment by CaryLandholt** [comment]
@dino- one more thing

try

``` bash
$ sudo npm install
```

**Comment by CaryLandholt** [comment]
Hi @dino-, I'm closing this bug due to inactivity.
Please let me know if you still have trouble, and I can work with you to resolve it.

Thanks
